---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  # - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: default
    verifier:
      name: inspec
    run_list:
      - recipe[chef_example::default]
    attributes:
