name             'chef_example'
maintainer       'Vinodh'
maintainer_email 'aluvinodh@gmail.com'
license          'All rights reserved'
description      'Installs/Configures java and nginx'
long_description 'Installs/Configures java and nginx'
version          '0.1.0'
issues_url 'jira_url'
source_url 'git_url'

depends 'selinux', '~> 0.5'
depends 'java', '~> 1.42'
